version: "3"
services:
  mongo_db:
    image: mongo
    ports:
      - 27019:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=natours-app
      - MONGO_INITDB_ROOT_PASSWORD=minyong123

  mongo_seeder:
    image: mongo_seeder
    depends_on:
      - mongo_db
